### ISSUE TITLE
Can't install drunnerc

### ISSUE THREAD

**Issue by infmon** [j842/drunnerc#4]
I know drunnerc isn't ready for use yet, but a few notes on the install process:

1) Can't install at all without doing "apt-get install build-essential g++-multilib libboost-all-dev".  The error is "./drunner-install: error while loading shared libraries: libboost_filesystem.so.1.55.0: cannot open shared object file: No such file or directory"

2) After installing the requirements, still can't install.  The output is:
DEBUG|2016/1/29 8:59| dRunner C++, version 0.1 r.342 - Sun Feb 28 23:00:39 NZDT 2016
|DEBUG|2016/1/29 8:59| Username: letmein,  Docker OK: YES, drunner-install path: /home/letmein
|DEBUG|2016/1/29 8:59| Created /home/letmein/drunner
|DEBUG|2016/1/29 8:59| Created /home/letmein/drunner/temp/services
|INFO |2016/1/29 8:59| Creating /home/letmein/bin
|DEBUG|2016/1/29 8:59| Pulling Docker image drunner/install-rootutils
|INFO |2016/1/29 8:59| Successfully pulled drunner/install-rootutils
|DEBUG|2016/1/29 8:59| Created /home/letmein/drunner/services
|ERROR|2016/1/29 8:59| Couldn't write to /home/letmein/drunner/support/validator-image

If I 'mkdir drunner/support', the install script then works, although drunner itself seems a bit broken (or else it's working differently to the old one :)

**Comment by j842** [comment]
Resolved.

**Comment by j842** [comment]
(that is, resolved in source, the downloadable executable has not been updated yet).
